Add topic and group exclusion parameters
danielqsj/kafka_exporter pull request #379
Opened 2023-03-20 20:46 UTC by bluesliverx

Related to #91 #103 #104 #127 #170 #217 and #93 (but solves it a different way that allows for both inclusion and exclusion). These PRs all seem to be out of date and have conflicts, so I took the main implementation from both and included them in this new PR. I'm happy to close and improve old PRs, but it would just be more work at this point.

Hopefully this can finally get some traction and get in since our kafka exporter pods are having a lot of trouble with some canary/health check consumer groups that don't need to be reported.

2023-05-22 05:40 UTC, danielqsj requested changes

2023-05-22 05:40 UTC, danielqsj commented on README.md
> +| topic.exclude                | .*             | Regex that determines which topics to exclude                                                                                          |
.*  -> ^$

2023-05-22 05:40 UTC, danielqsj commented
@bluesliverx thanks, pls fix the typo

2023-05-22 13:21 UTC, bluesliverx commented on README.md
> +| topic.exclude                | .*             | Regex that determines which topics to exclude                                                                                          |
Good catch, fixed!

2023-05-23 02:04 UTC, danielqsj commented
LGTM

2023-05-23 02:05 UTC, merged